version: "3.3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:postgres@db/postgres
      - DTC_ENVIRONMENT=dev
      - PYTHONIOENCODING=utf-8
      - LANG=en_US.UTF-8